### ISSUE TITLE
Remove bash hack

### ISSUE THREAD

**Issue by davetcoleman** [davetcoleman/moveit_docker#1]
From feedback from @ruffsl I'm using this hack so that `source /opt/ros/indigo/setup.bash` works:

```
# HACK, bad practice
RUN rm /bin/sh \
    && ln -s /bin/bash /bin/sh
```

How can we remove this "bad practice"? I don't fully understand why this is needed.

**Comment by davetcoleman** [comment]
@scpeters thoughts on this?

**Comment by scpeters** [comment]
Sorry, I am only a docker apprentice; @ruffsl is the master

**Comment by davetcoleman** [comment]
:neckbeard:

**Comment by ruffsl** [comment]
Well... :thought_balloon:  It's more like it's just unconventional. I'd be opposed of switching the default shell from underneath users in a release image, but with the devel image, it's convenience to enable the sourcing of the ros setup for catkin is rather practical, while keeping everything in a single file has fewer points of failure, like forgetting to make the script executable before commit/pushing it to github with the Dockerfile. 

See the comments on a related [stackoverflow answer](http://stackoverflow.com/a/25423366/2577586) for a note on performance; but seeing as we only need it for one command (that takes orders of magnatudes longer than the shell's startup time), I'd say leave it be unless we encounter a resion to do otherwise.

**Comment by davetcoleman** [comment]
I see the comment:

> ln -s /bin/bash /bin/sh this is a terrible idea. ubuntu targets /bin/sh to dash for a reason. dash is a fully posix shell which is orders of magnitude faster than bash. linking /bin/sh to bash will drastically reduce your server's performance. cite: wiki.ubuntu.com/DashAsBinSh

But I agree with you, we should not worry about it

**Comment by davetcoleman** [comment]
@ruffsl I have a similar issue, not sure if its related to the above hack...

When I'm in an interactive shell with Docker there are certain things in bash/my terminal that do not work the same. Scrolling up and down seems a little funky. The show-stopper I'm on right now is that when I run `git diff` I cannot scroll up and down to see the changes. Same thing for `man` e.g. `man touch` (lol I just realized that's a funny example). Any idea why this is not working? I've been googling but I'm not sure how to describe my problem. I don't know if I need bash shell or sh shell or something else.

**Comment by ruffsl** [comment]
I just tried 

``` terminal
$ docker run -it ros:indigo
$ apt update
$ apt install man
$ man git
```

and it worked fine, but not so for `ros:kinetic`. It appears that Ubuntu Xenial base image doesn't have `less` installed by default, only `more`. @tfoote helped me find this out. You could add it to the dev image.

P.S. That's why formatted the dockerfiles such that package appeared alphabetically on indented new lines, and changes to the docker file could easily be read by users in git diffs.

I guess `less` is better than `more` in this case.

**Comment by davetcoleman** [comment]
apt-get install less fixed my issue!

+1 to adding it to the dev image

I also reported the [bug on launchpad](https://bugs.launchpad.net/ubuntu/+source/less/+bug/1596091)

**Comment by tfoote** [comment]
I feel like this is more of a developer tool than a core component. It only takes ~ 10 seconds to install less including the apt-get update which is ~7 seconds which is shared across any other developer/debugging tools you want to install. Similarly I'd recommend against adding things like emacs and vi etc into the base images. If you want to do a personal layer on top specific to your use cases that's reasonable, but I'd avoid imposing tool preferences generally.

**Comment by davetcoleman** [comment]
I agree with you except I think this is an Ubuntu regression, as I stated in my launchpad report:

> This is bad for programs like "man" or "diff" that use less' scrolling capability.

**Comment by tfoote** [comment]
I definitely wouldn't call it a bug. The PAGER used is a configuration
option in your environment that man and git both use. They have just
changed the default to a lower level one to decrease overhead.

The pager is an abstraction used for interfacing in the terminal:
https://en.wikipedia.org/wiki/Terminal_pager
You can configure it using the PAGER environment variable, just like you
set your EDITOR
https://unix.stackexchange.com/questions/213367/where-do-editor-pager-browser-environment-variables-come-from

You can see the order that man resolves pagers in the man manpage. Also
copied here:
https://askubuntu.com/questions/623992/what-is-the-default-pager-used-by-man-pages

​

**Comment by davetcoleman** [comment]
Thanks for all those links, I didn't know about PAGERs. I'm a little amused scrolling is something we bother thinking about still - wasn't that solved in the 60's? Seems like scrolling in a terminal should just work in a Docker image, regardless of space requirements for the simple function.
